/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VoixRouteImport } from './routes/voix'
import { Route as ConfirmationOrderNumberRouteImport } from './routes/confirmation.$orderNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VoixRoute = VoixRouteImport.update({
  id: '/voix',
  path: '/voix',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationOrderNumberRoute = ConfirmationOrderNumberRouteImport.update({
  id: '/confirmation/$orderNumber',
  path: '/confirmation/$orderNumber',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/voix': typeof VoixRoute
  '/confirmation/$orderNumber': typeof ConfirmationOrderNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/voix': typeof VoixRoute
  '/confirmation/$orderNumber': typeof ConfirmationOrderNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/voix': typeof VoixRoute
  '/confirmation/$orderNumber': typeof ConfirmationOrderNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/voix' | '/confirmation/$orderNumber'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/voix' | '/confirmation/$orderNumber'
  id: '__root__' | '/' | '/voix' | '/confirmation/$orderNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VoixRoute: typeof VoixRoute
  ConfirmationOrderNumberRoute: typeof ConfirmationOrderNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voix': {
      id: '/voix'
      path: '/voix'
      fullPath: '/voix'
      preLoaderRoute: typeof VoixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation/$orderNumber': {
      id: '/confirmation/$orderNumber'
      path: '/confirmation/$orderNumber'
      fullPath: '/confirmation/$orderNumber'
      preLoaderRoute: typeof ConfirmationOrderNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VoixRoute: VoixRoute,
  ConfirmationOrderNumberRoute: ConfirmationOrderNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
